title: Kent Maps Online

description: Website Description (goes in footer).

author:
  name: Site owner name
  email: site_owner@some_domain.com

github:
  owner_name: kent-map
  repository_name: kent-maps-online
  source:
    branch: main

nav_pages:
  - index.md
  - _articles/index.md
  - _admin/index.md
  - _examples/index.md
  - about/index.md
  # - contact.md

collections:
  admin:
    output: true
    permalink: /:collection/:path/
  articles:
    output: true
    permalink: /:collection/:path/
  examples:
    output: true
    permalink: /:collection/:path/


show_excerpts: true
show_rss_feed: false
max-width: 1000px

footer:
  show_github_link: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
